### ISSUE TITLE
Trace is not detailed enough (Function/odoo.service.wsgi_server:application (99.9%)

### ISSUE THREAD

**Issue by tmotyl** [hibou-io/odoo-newrelic#11]
I have odoo 10 behind an nginx. The profile looks like:
![image](https://user-images.githubusercontent.com/515397/144874757-add3b5d5-83fd-4a82-af0e-969d5e46a24a.png)

I would expect to see much more detailed stack trace/graph - 99.9% of the time is spent in Function/odoo.service.wsgi_server:application, and there are no more details about method calls. Only postgress calls are shown.

**Comment by tmotyl** [comment]
this is similar to https://github.com/hibou-io/odoo-newrelic/issues/4, but for proxied installation of odoo

**Comment by jaredkipe** [comment]
This is still the case even in 15 and the latest python `newrelic` module.

**Comment by tmotyl** [comment]
Hi @jaredkipe 

Odoo is not on the list of frameworks supported out of the box:
https://docs.newrelic.com/docs/apm/agents/python-agent/getting-started/instrumented-python-packages/

So this issue could be solved by writing new relic custom instrumentation.
https://docs.newrelic.com/docs/apm/agents/python-agent/custom-instrumentation/python-custom-instrumentation/

**Comment by jaredkipe** [comment]
@tmotyl 

https://github.com/hibou-io/odoo-newrelic/commit/e77d9a45c326a157eabbfb14829883d47dfc8dac 

I've added some configurable tracing, with defaults for some modest model methods that can be helpful.
