### ISSUE TITLE
Odoo 8 compatibility

### ISSUE THREAD

**Issue by Nickske157** [hibou-io/odoo-newrelic#3]
Dear jaredkipe,

Do you know if the module works with odoo 8?
If not, can you make it compatible?

Kind Regards

Nick Geoffroy

**Comment by jaredkipe** [comment]
I don't know for certain, but you could try the 9 version (on a non-production site of course) .  If it doesn't work, I'd certainly accept a pull request for it.

**Comment by billandr** [comment]
I'd like it to ignore other urls (e.g. oauth urls) - what's the best-practice way of adding paths to ignore?

**Comment by jaredkipe** [comment]
@billandr 
Specifically about Odoo 8?

Ultimately I don't know if it is best practice, but in the same way that I ignored the bus routes you could extend the oauth controller of your choice and ignore individual routes like that.
https://github.com/hibou-io/odoo-newrelic/blob/10.0/newrelic/controllers/main.py

**Comment by billandr** [comment]
I apologize; I should have created a new topic; version 10.x - but either way; I understand the solution - thanks!
