### ISSUE TITLE
Get trace data on odoo.service.wsgi_server:application_unproxied

### ISSUE THREAD

**Issue by piqoni** [hibou-io/odoo-newrelic#4]
Hi, thanks for the module - it's awesome. Just installed and it works but I dont see any data on `application_unproxied` in NewRelic. It's causing the slowness all over my Odoo instance. Do you have any suggestion? 

![image](https://user-images.githubusercontent.com/3144671/38684259-9436cdca-3e6f-11e8-9d7c-334cad772cd6.png)

**Comment by jaredkipe** [comment]
Ultimately that represents 'the python VM code'.  I honestly do not remember if it was more in-depth in earlier versions of Odoo (e.g. 9) or different levels of NewRelic. I've only ever used the free version and they have changed the amount of information I have access to several times over the years.
In general, how fast is your Odoo instance responding? During typical load I get ~30-200ms loading time.

**Comment by piqoni** [comment]
Thanks for the reply. Our odoo is fast enough on average (~400ms under heavy load) but we have some specific cases which are slow (24 seconds and above, etc) and that's why we installed the module so perhaps we could identify what's going on. I'll research this, but meanwhile found out this: 
![image](https://user-images.githubusercontent.com/3144671/38722348-f8d8220e-3efd-11e8-98cd-d820e7de2bc2.png)
Also the Odoo instance is behind a reverse proxy, but I'm not sure at this point if that plays a role in this.

**Comment by jaredkipe** [comment]
Mine is behind a reverse proxy as well, I've never run Odoo directly without nginx infront of it.  (even in dev)

Reading through the agent docs, nothing stands out to me as a magic "Go ahead and profile my code".

Unfortunately I don't have a lot of time to try to improve it right now. Maybe I can take a stab at it when I migrate this to 11.0 (whenever Odoo gets me my upgrade....).

**Comment by hemangb-emipro** [comment]
Hi @jaredkipe 

I am also having the same issue that the wsgi_server:application_unproxied is consuming too much time.

Is there any update on this. I am using it for v11.

Thanks.

**Comment by jaredkipe** [comment]
Closing, as I don't believe this is something I can fix, and if it is we must start working in newer version of Odoo like 15

**Comment by jaredkipe** [comment]
@hemangb-emipro  @piqoni 

https://github.com/hibou-io/odoo-newrelic/commit/e77d9a45c326a157eabbfb14829883d47dfc8dac 

I've added some configurable tracing, with defaults for some modest model methods that can be helpful.

**Comment by hemangb-emipro** [comment]
Thank you @piqoni
