### ISSUE TITLE
odoo 11 & odoo 12

### ISSUE THREAD

**Issue by foutoucour** [hibou-io/odoo-newrelic#5]
Hello Hiboux,

Did you give a try to port the module on odoo 11 and odoo 12 ?
We would be interested to use the module on our side, but I don't know if it is compatible with python 3

Thank you,
Jordi

**Comment by eLBati** [comment]
Hi @foutoucour I installed on v12 and it seems to work. Are you aware of any drawbacks?
Thanks

**Comment by eLBati** [comment]
Uh, it seems this https://github.com/hibou-io/odoo-newrelic/issues/8 also happens in v12
