### ISSUE TITLE
V13 app 

### ISSUE THREAD

**Issue by Yenthe666** [hibou-io/odoo-newrelic#6]
Hi @jaredkipe,

Thanks a lot for this module!
I've just tested it and deployed it for a V13 instance and it still works fine. Since I can't create branches in your repository I'll link you mine:
https://github.com/Yenthe666/odoo-newrelic/tree/13.0
Any chance you can make a 13.0 branch from your 11.0 branch so I can make a PR for V13?

P.S: Have you ever considered differently so that cron jobs etc are also tracked? Now it uses longpolling so this means only user-interface triggered behaviour is caught.

**Comment by jaredkipe** [comment]
To be honest, I don't really use NewRelic much anymore, so I haven't looked at this for quite some time. 

I made a branch for 12.0 and 13.0 so that you can make merge requests, much appreciated!

Eventually I should move this into `suite`...

**Comment by Yenthe666** [comment]
Basically done in https://github.com/hibou-io/odoo-newrelic/commit/cdf642d7b85fa86e0fdc77118e7739bf6fde590c 🥳
